/* ------------------------------------------------------------------ */
/* OceanScope 3D — mock ocean data engine                              */
/*                                                                     */
/* All values are generated by deterministic, seeded functions so the  */
/* prototype behaves like a stable scientific dataset: the same        */
/* filters always return the same numbers. Replace these functions     */
/* with FastAPI calls later (see src/services/api.ts).                 */
/* ------------------------------------------------------------------ */

import type {
  Depth,
  DepthAgreement,
  ErrorBin,
  ErrorCell,
  MatchRecord,
  PlatformType,
  Region,
  RegionKey,
  ScatterPoint,
  SeriesPoint,
  Station,
  StatusLevel,
  VariableDef,
  VariableKey,
} from "../types";

/* ----------------------------- time ------------------------------- */

export const DAYS = 30; // one-month observation window
export const MONTH_LABEL = "January 2026";

function pad(n: number) {
  return n < 10 ? `0${n}` : `${n}`;
}
export function isoDate(day: number): string {
  return `2026-01-${pad(Math.min(Math.max(day, 1), 30))}`;
}
export function shortDate(day: number): string {
  return `${pad(Math.min(Math.max(day, 1), 30))} Jan`;
}

/* ----------------------- deterministic PRNG ------------------------ */

export function hashStr(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
/** Symmetric pseudo-random noise in [-spread, spread], stable per key. */
export function noise(key: string, spread = 1): number {
  return (mulberry32(hashStr(key))() * 2 - 1) * spread;
}

function gauss(lon: number, lat: number, cLon: number, cLat: number, sLon: number, sLat: number): number {
  const dx = (lon - cLon) / sLon;
  const dy = (lat - cLat) / sLat;
  return Math.exp(-(dx * dx + dy * dy));
}
const clamp = (v: number, lo: number, hi: number) => Math.min(hi, Math.max(lo, v));

/* --------------------------- geography ----------------------------- */

export const MAP_EXTENT = { lonMin: 50, lonMax: 100, latMin: 0, latMax: 28 };

/** Simplified coastline of South Asia → Malay Peninsula (illustrative). */
export const MAINLAND: [number, number][] = [
  [50, 26.9], [53.8, 26.6], [57.2, 25.7], [61.4, 25.2], [63.6, 25.2],
  [66.3, 24.7], [68.0, 23.7], [69.4, 22.4], [69.9, 21.8], [70.15, 20.7],
  [71.9, 20.9], [72.55, 21.6], [72.95, 20.6], [72.8, 19.2], [72.95, 18.2],
  [73.5, 16.3], [73.85, 15.4], [74.4, 14.3], [74.8, 12.9], [76.1, 10.0],
  [76.9, 8.85], [77.55, 8.05], [78.15, 9.1], [78.95, 9.45], [79.35, 10.35],
  [79.9, 10.85], [80.2, 12.2], [80.45, 13.5], [80.25, 15.8], [80.6, 16.35],
  [81.6, 16.4], [82.4, 16.9], [83.3, 18.0], [84.1, 18.4], [85.1, 19.7],
  [86.4, 20.1], [87.0, 20.85], [87.15, 21.65], [88.1, 21.6], [89.0, 21.75],
  [90.0, 22.1], [91.0, 22.4], [91.9, 22.3], [92.9, 20.7], [93.4, 19.9],
  [94.2, 17.5], [94.5, 16.1], [95.7, 15.6], [97.2, 15.2], [98.2, 13.4],
  [98.7, 11.2], [99.0, 8.8], [99.8, 6.9], [100.6, 6.4], [100.6, 28.6],
  [49.4, 28.6],
];

export const SRI_LANKA: [number, number][] = [
  [79.7, 9.0], [80.4, 9.75], [81.3, 8.55], [81.9, 7.2], [81.55, 6.35],
  [80.95, 5.92], [80.0, 5.94], [79.68, 6.55], [79.62, 7.6], [79.68, 8.5],
];

/** North-western Sumatra wedge (bottom-right corner of the map). */
export const SUMATRA: [number, number][] = [
  [95.3, 5.95], [96.9, 5.4], [98.3, 4.35], [99.5, 3.2], [100.6, 1.85],
  [100.6, 6.25], [97.5, 6.4], [95.3, 6.25],
];

/** Andaman & Nicobar island chain, as [lon, lat, rLon, rLat] ellipses. */
export const ANDAMANS: [number, number, number, number][] = [
  [92.85, 13.15, 0.16, 0.5],
  [92.85, 12.3, 0.17, 0.55],
  [92.68, 11.55, 0.22, 0.6],
  [92.42, 10.65, 0.19, 0.5],
  [92.72, 9.15, 0.18, 0.32],
  [92.95, 8.0, 0.17, 0.38],
  [93.05, 7.05, 0.22, 0.6],
];

/** Lakshadweep & Maldives atolls, drawn as small dots. */
export const ATOLLS: [number, number][] = [
  [72.6, 11.6], [72.2, 10.6], [73.0, 8.4], [73.2, 6.9], [73.35, 4.2], [73.5, 3.1],
];

/** Point-in-polygon (ray casting) on lon/lat space. */
export function inPolygon(lon: number, lat: number, poly: [number, number][]): boolean {
  let inside = false;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [xi, yi] = poly[i];
    const [xj, yj] = poly[j];
    const intersect =
      yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi;
    if (intersect) inside = !inside;
  }
  return inside;
}

export function isLand(lon: number, lat: number): boolean {
  if (inPolygon(lon, lat, MAINLAND)) return true;
  if (inPolygon(lon, lat, SRI_LANKA)) return true;
  if (inPolygon(lon, lat, SUMATRA)) return true;
  for (const [cx, cy, rx, ry] of ANDAMANS) {
    const dx = (lon - cx) / rx;
    const dy = (lat - cy) / ry;
    if (dx * dx + dy * dy < 1) return true;
  }
  for (const [ax, ay] of ATOLLS) {
    if (Math.abs(lon - ax) < 0.1 && Math.abs(lat - ay) < 0.1) return true;
  }
  return false;
}

/* ---------------------------- regions ------------------------------ */

export const REGIONS: Region[] = [
  {
    key: "bob",
    label: "Bay of Bengal",
    bbox: { lonMin: 80, lonMax: 95.5, latMin: 5, latMax: 22.6 },
    blurb: "Strong river discharge, warm pool dynamics and cyclone activity.",
  },
  {
    key: "arabian",
    label: "Arabian Sea",
    bbox: { lonMin: 58, lonMax: 76.5, latMin: 5, latMax: 23.5 },
    blurb: "High-salinity basin with seasonal upwelling along the west coast.",
  },
  {
    key: "indian",
    label: "Indian Ocean",
    bbox: { lonMin: 55, lonMax: 100, latMin: 0, latMax: 20 },
    blurb: "Basin-wide view across the North Indian Ocean.",
  },
  {
    key: "tn",
    label: "Tamil Nadu Coast",
    bbox: { lonMin: 77.5, lonMax: 84.5, latMin: 7, latMax: 14.6 },
    blurb: "Coastal upwelling zone monitored by the nearshore buoy network.",
  },
  {
    key: "andaman",
    label: "Andaman Sea",
    bbox: { lonMin: 91.5, lonMax: 99, latMin: 5.5, latMax: 15.5 },
    blurb: "Semi-enclosed basin exchanging water through the Andaman passages.",
  },
];

export function regionByKey(key: RegionKey): Region {
  return REGIONS.find((r) => r.key === key)!;
}

/* --------------------------- variables ----------------------------- */

export const VARIABLES: VariableDef[] = [
  {
    key: "temperature",
    label: "Sea Temperature",
    short: "Temperature",
    unit: "°C",
    decimals: 2,
    palette: ["#1D4ED8", "#0284C7", "#06B6D4", "#FDE047", "#F97316", "#DC2626"],
    domain: (d) => (d === 0 ? [25, 31] : d === 50 ? [21, 28] : d === 100 ? [15.5, 22.5] : [10, 16.5]),
    goodBelow: 0.4,
    moderateBelow: 0.9,
    explainer: "How warm the seawater is. Temperature drives cyclones, monsoon rainfall and marine ecosystems.",
  },
  {
    key: "salinity",
    label: "Salinity",
    short: "Salinity",
    unit: "PSU",
    decimals: 2,
    palette: ["#99F6E4", "#5EEAD4", "#2DD4BF", "#0D9488", "#0F766E", "#134E4A"],
    domain: () => [30, 36.5],
    goodBelow: 0.2,
    moderateBelow: 0.5,
    explainer: "Salt content of seawater in Practical Salinity Units. Fresh river water lowers salinity near the coast.",
  },
  {
    key: "current",
    label: "Ocean Currents",
    short: "Current Speed",
    unit: "m/s",
    decimals: 2,
    palette: ["#EDE9FE", "#DDD6FE", "#C4B5FD", "#8B5CF6", "#6D28D9", "#4C1D95"],
    domain: () => [0, 1.5],
    goodBelow: 0.12,
    moderateBelow: 0.35,
    explainer: "Speed of horizontal water movement. Currents transport heat, nutrients, larvae and pollutants.",
  },
];

export function variableByKey(key: VariableKey): VariableDef {
  return VARIABLES.find((v) => v.key === key)!;
}

/** Interpolate a palette at t in [0,1] (linear RGB). */
export function paletteColor(palette: string[], t: number): string {
  const x = clamp(t, 0, 1) * (palette.length - 1);
  const i = Math.min(Math.floor(x), palette.length - 2);
  const f = x - i;
  const a = hex(palette[i]);
  const b = hex(palette[i + 1]);
  const mix = a.map((v, k) => Math.round(v + (b[k] - v) * f));
  return `rgb(${mix[0]},${mix[1]},${mix[2]})`;
}
function hex(h: string): number[] {
  return [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16)];
}

export function valueColor(variable: VariableKey, value: number, depth: number): string {
  const def = variableByKey(variable);
  const [lo, hi] = def.domain(depth);
  return paletteColor(def.palette, (value - lo) / (hi - lo));
}

/* ---------------------------- stations ----------------------------- */

export const STATIONS: Station[] = [
  { id: "ARGO-IN-1024", name: "Central Bay Argo", platform: "Argo Float", lon: 88.2, lat: 12.4, region: "bob", depths: [0, 50, 100, 200], qc: "passed", status: "active", lastUpdate: "31 Jan 2026, 05:30 IST" },
  { id: "ARGO-IN-1031", name: "North Bay Argo", platform: "Argo Float", lon: 90.1, lat: 16.8, region: "bob", depths: [0, 50, 100, 200], qc: "flagged", status: "active", lastUpdate: "30 Jan 2026, 22:10 IST" },
  { id: "ARGO-IN-0987", name: "Lakshadweep Argo", platform: "Argo Float", lon: 69.5, lat: 12.8, region: "arabian", depths: [0, 50, 100, 200], qc: "passed", status: "active", lastUpdate: "31 Jan 2026, 04:45 IST" },
  { id: "ARGO-IN-0954", name: "Konkan Argo", platform: "Argo Float", lon: 73.2, lat: 18.4, region: "arabian", depths: [0, 50, 100, 200], qc: "passed", status: "active", lastUpdate: "31 Jan 2026, 03:15 IST" },
  { id: "ARGO-IN-1188", name: "Ceylon Argo", platform: "Argo Float", lon: 83.6, lat: 7.2, region: "bob", depths: [0, 50, 100, 200], qc: "passed", status: "active", lastUpdate: "31 Jan 2026, 06:05 IST" },
  { id: "BUOY-BOB-07", name: "Chennai Coastal Buoy", platform: "Moored Buoy", lon: 80.9, lat: 13.7, region: "tn", depths: [0, 50], qc: "passed", status: "active", lastUpdate: "31 Jan 2026, 07:00 IST" },
  { id: "BUOY-BOB-08", name: "Paradip Buoy", platform: "Moored Buoy", lon: 85.3, lat: 18.5, region: "bob", depths: [0, 50], qc: "passed", status: "active", lastUpdate: "31 Jan 2026, 06:40 IST" },
  { id: "BUOY-BOB-11", name: "South Bay Buoy", platform: "Moored Buoy", lon: 89.6, lat: 8.4, region: "bob", depths: [0, 50], qc: "passed", status: "maintenance", lastUpdate: "29 Jan 2026, 18:20 IST" },
  { id: "BUOY-AS-04", name: "Goa Offshore Buoy", platform: "Moored Buoy", lon: 66.8, lat: 18.9, region: "arabian", depths: [0, 50], qc: "passed", status: "active", lastUpdate: "31 Jan 2026, 05:50 IST" },
  { id: "BUOY-AND-02", name: "Port Blair Buoy", platform: "Moored Buoy", lon: 91.9, lat: 11.3, region: "andaman", depths: [0, 50], qc: "passed", status: "active", lastUpdate: "31 Jan 2026, 06:25 IST" },
  { id: "RAMA-IN-04", name: "Andaman Deep Mooring", platform: "Moored Array", lon: 93.4, lat: 8.1, region: "andaman", depths: [0, 50, 100, 200], qc: "passed", status: "active", lastUpdate: "31 Jan 2026, 05:10 IST" },
  { id: "SHIP-IO-221", name: "ORV Sagar Kanya", platform: "Ship Observation", lon: 76.4, lat: 4.1, region: "indian", depths: [0, 50, 100, 200], qc: "passed", status: "active", lastUpdate: "30 Jan 2026, 21:30 IST" },
  { id: "SHIP-IO-215", name: "FV Sagar Sampada", platform: "Ship Observation", lon: 72.8, lat: 16.2, region: "arabian", depths: [0, 50, 100, 200], qc: "passed", status: "active", lastUpdate: "31 Jan 2026, 02:40 IST" },
  { id: "SHIP-IO-233", name: "Coastal Survey Vessel", platform: "Ship Observation", lon: 84.6, lat: 19.4, region: "bob", depths: [0, 50, 100, 200], qc: "passed", status: "active", lastUpdate: "31 Jan 2026, 01:55 IST" },
];

export function stationsInRegion(region: RegionKey): Station[] {
  return STATIONS.filter((s) => s.region === region || region === "indian");
}
export function stationById(id: string): Station | undefined {
  return STATIONS.find((s) => s.id === id);
}

export const PLATFORM_STYLE: Record<PlatformType, { color: string; marker: "circle" | "diamond" | "triangle" | "square" }> = {
  "Argo Float": { color: "#2DD4BF", marker: "diamond" },
  "Moored Buoy": { color: "#14B8A6", marker: "circle" },
  "Ship Observation": { color: "#0EA5E9", marker: "triangle" },
  "Moored Array": { color: "#34D399", marker: "square" },
};

/* ---------------------- physical field model ----------------------- */

function tempAtDepth(depth: number): number {
  const pts: [number, number][] = [[0, 28.7], [50, 26.2], [100, 20.0], [200, 14.4]];
  if (depth <= 0) return pts[0][1];
  for (let i = 1; i < pts.length; i++) {
    if (depth <= pts[i][0]) {
      const [d0, v0] = pts[i - 1];
      const [d1, v1] = pts[i];
      return v0 + ((v1 - v0) * (depth - d0)) / (d1 - d0);
    }
  }
  return pts[pts.length - 1][1];
}

/** Smooth "truth" field of the selected variable at lon/lat/depth. */
export function fieldValue(variable: VariableKey, lon: number, lat: number, depth: number, day = 15): number {
  if (variable === "temperature") {
    const fall = clamp(depth / 200, 0, 1);
    let t = tempAtDepth(depth);
    t += (-0.045 * (lat - 8) + 0.02 * (lon - 84)) * (1 - 0.6 * fall);
    t += 1.15 * gauss(lon, lat, 84.5, 7.5, 7, 4.5) * (1 - fall);
    t -= 0.85 * gauss(lon, lat, 80.4, 12.0, 2.5, 7) * (1 - fall); // TN upwelling
    t += 0.55 * gauss(lon, lat, 94.5, 10.5, 4, 5) * (1 - 0.5 * fall);
    t += Math.sin(day / 5.1) * 0.35 * (1 - fall) + day * 0.016;
    return clamp(t, 4, 31.5);
  }
  if (variable === "salinity") {
    const fall = clamp(depth / 250, 0, 1);
    let s = 33.05 + depth * 0.0011;
    s += 1.55 * gauss(lon, lat, 65.5, 17, 10, 9);
    s -= 2.1 * gauss(lon, lat, 89.5, 20.5, 7.5, 5) * (1 - fall); // northern river plume
    s -= 0.55 * gauss(lon, lat, 80.9, 12.5, 3, 5) * (1 - fall);
    s += 0.3 * gauss(lon, lat, 94, 8, 5, 6);
    s += Math.sin(day / 6.3 + 1.2) * 0.07 * (1 - fall);
    return clamp(s, 29.6, 36.6);
  }
  // current speed
  let c = 0.16;
  c += 0.85 * gauss(lon, lat, 87.6, 15.0, 6, 5.5);
  c += 0.7 * gauss(lon, lat, 71.5, 8.2, 5.5, 4.5);
  c += 0.42 * gauss(lon, lat, 93.0, 7.2, 3, 3);
  c += 0.12 * Math.abs(Math.sin(lon * 0.35 + day * 0.1) * Math.cos(lat * 0.3));
  c *= 1 - clamp(depth / 350, 0, 0.75);
  return clamp(c, 0.05, 1.5);
}

/** Direction (degrees, clockwise from North) for current arrows. */
export function currentDirection(lon: number, lat: number, day = 15): number {
  const gyre = (cLon: number, cLat: number, strength: number, clockwise: boolean) => {
    const dx = lon - cLon;
    const dy = lat - cLat;
    const r = Math.hypot(dx, dy) + 0.001;
    const w = strength * Math.exp(-r / 7);
    // tangent angle (radians) around gyre centre
    const ang = Math.atan2(dx, dy) + (clockwise ? Math.PI / 2 : -Math.PI / 2);
    return { w, ang };
  };
  const g1 = gyre(87.6, 15.0, 1.4, false);
  const g2 = gyre(71.5, 8.2, 1.1, true);
  const g3 = gyre(93.0, 7.2, 0.8, false);
  // background west-bound equatorial flow + along-coast drift
  let x = Math.sin((215 * Math.PI) / 180) * 0.25;
  let y = Math.cos((215 * Math.PI) / 180) * 0.25;
  for (const g of [g1, g2, g3]) {
    x += Math.sin(g.ang) * g.w;
    y += Math.cos(g.ang) * g.w;
  }
  const deg = (Math.atan2(x, y) * 180) / Math.PI + noise(`dir|${lon.toFixed(1)}|${lat.toFixed(1)}|${day}`, 12);
  return (deg + 360) % 360;
}

/* --------------- observed vs model value generation ---------------- */

const HIGH_DEV_STATIONS = new Set(["BUOY-BOB-08", "SHIP-IO-233"]);

function biasFor(stationId: string, variable: VariableKey, depth: number): number {
  const depthScale = 1 + depth / 90;
  const base = noise(`${stationId}|${variable}|bias`, 1);
  const flagged = HIGH_DEV_STATIONS.has(stationId) ? Math.sign(base || 1) * 0.62 : 0;
  switch (variable) {
    case "temperature":
      return base * 0.62 * (1 + depth / 150) + flagged * (1.05 + depth / 150) + 0.04;
    case "salinity":
      return base * 0.18 * depthScale + flagged * 0.26 - 0.05;
    case "current":
      return base * 0.11 * depthScale + flagged * 0.15 - 0.02;
  }
}

export function observedValue(station: Station, variable: VariableKey, depth: number, day: number): number {
  const f = fieldValue(variable, station.lon, station.lat, depth, day);
  const amp = variable === "temperature" ? 0.22 : variable === "salinity" ? 0.1 : 0.1;
  const n = noise(`${station.id}|${variable}|${depth}|${day}|obs`, amp);
  return f + n;
}

export function modelValue(station: Station, variable: VariableKey, depth: number, day: number): number {
  // The model is a *smoothed* version of the truth plus a persistent bias:
  const lon = station.lon + 0.35; // grid-cell offset mimics coarse resolution
  const lat = station.lat - 0.28;
  const f = fieldValue(variable, lon, lat, depth, day);
  const smoothNoise = noise(`${station.id}|${variable}|${depth}|${Math.floor(day / 3)}|mdl`, variable === "temperature" ? 0.12 : 0.06);
  return f + biasFor(station.id, variable, depth) + smoothNoise;
}

export function statusFor(variable: VariableKey, diff: number): StatusLevel {
  const def = variableByKey(variable);
  const a = Math.abs(diff);
  if (a < def.goodBelow) return "good";
  if (a < def.moderateBelow) return "moderate";
  return "high";
}

export const STATUS_META: Record<StatusLevel, { label: string; short: string; color: string; bg: string; text: string; border: string }> = {
  good: { label: "Good Agreement", short: "Good", color: "#15803D", bg: "bg-emerald-50", text: "text-emerald-700", border: "border-emerald-200" },
  moderate: { label: "Moderate Agreement", short: "Moderate", color: "#B45309", bg: "bg-amber-50", text: "text-amber-700", border: "border-amber-200" },
  high: { label: "High Deviation", short: "Deviation", color: "#B91C1C", bg: "bg-red-50", text: "text-red-700", border: "border-red-200" },
};

/* ------------------- series & aggregate computations --------------- */

export interface FilterSpec {
  region: RegionKey;
  variable: VariableKey;
  depth: Depth;
  fromDay: number;
  toDay: number;
}

export function stationSeries(station: Station, variable: VariableKey, depth: number, fromDay = 1, toDay = DAYS): SeriesPoint[] {
  const out: SeriesPoint[] = [];
  for (let d = fromDay; d <= toDay; d++) {
    const obs = observedValue(station, variable, depth, d);
    const mdl = modelValue(station, variable, depth, d);
    out.push({ date: shortDate(d), day: d, observed: +obs.toFixed(3), model: +mdl.toFixed(3), diff: +(mdl - obs).toFixed(3) });
  }
  return out;
}

/** Regional mean time series (average of all stations inside the region). */
export function regionSeries(spec: FilterSpec): SeriesPoint[] {
  const stations = stationsInRegion(spec.region).filter((s) => s.depths.includes(spec.depth));
  const out: SeriesPoint[] = [];
  for (let d = spec.fromDay; d <= spec.toDay; d++) {
    let o = 0, m = 0;
    for (const s of stations) {
      o += observedValue(s, spec.variable, spec.depth, d);
      m += modelValue(s, spec.variable, spec.depth, d);
    }
    const n = stations.length || 1;
    out.push({ date: shortDate(d), day: d, observed: +(o / n).toFixed(3), model: +(m / n).toFixed(3), diff: +((m - o) / n).toFixed(3) });
  }
  return out;
}

export function scatterData(spec: FilterSpec): ScatterPoint[] {
  const stations = stationsInRegion(spec.region).filter((s) => s.depths.includes(spec.depth));
  const out: ScatterPoint[] = [];
  for (const s of stations) {
    for (let d = spec.fromDay; d <= spec.toDay; d += 2) {
      const obs = +observedValue(s, spec.variable, spec.depth, d).toFixed(3);
      const mdl = +modelValue(s, spec.variable, spec.depth, d).toFixed(3);
      out.push({ id: `${s.id}-${d}`, stationId: s.id, model: mdl, observed: obs, status: statusFor(spec.variable, mdl - obs) });
    }
  }
  return out;
}

export function matchRecords(spec: FilterSpec): MatchRecord[] {
  const stations = stationsInRegion(spec.region).filter((s) => s.depths.includes(spec.depth));
  const out: MatchRecord[] = [];
  for (const s of stations) {
    for (let d = spec.fromDay; d <= spec.toDay; d += 2) {
      const obs = observedValue(s, spec.variable, spec.depth, d);
      const mdl = modelValue(s, spec.variable, spec.depth, d);
      const diff = mdl - obs;
      out.push({
        stationId: s.id,
        platform: s.platform,
        date: shortDate(d),
        lat: s.lat,
        lon: s.lon,
        depth: spec.depth,
        model: +mdl.toFixed(3),
        observed: +obs.toFixed(3),
        diff: +diff.toFixed(3),
        status: statusFor(spec.variable, diff),
      });
    }
  }
  return out;
}

export function validationMetrics(spec: FilterSpec): { mae: number; rmse: number; bias: number; n: number } {
  const recs = matchRecords(spec);
  if (!recs.length) return { mae: 0, rmse: 0, bias: 0, n: 0 };
  let sa = 0, ss = 0, sb = 0;
  for (const r of recs) {
    sa += Math.abs(r.diff);
    ss += r.diff * r.diff;
    sb += r.diff;
  }
  const n = recs.length;
  return { mae: sa / n, rmse: Math.sqrt(ss / n), bias: sb / n, n };
}

/** Deterministic data coverage %, slightly lower at deeper levels. */
export function coverageFor(spec: FilterSpec): number {
  const regionPenalty: Record<RegionKey, number> = { bob: 5.1, arabian: 6.2, indian: 7.4, tn: 9.8, andaman: 8.6 };
  const varPenalty = spec.variable === "current" ? 2.6 : spec.variable === "salinity" ? 1.2 : 0;
  const v = 97.5 - regionPenalty[spec.region] - spec.depth * 0.02 - varPenalty;
  return clamp(v, 80, 98.5);
}

export function depthAgreement(spec: FilterSpec): DepthAgreement[] {
  const depths: Depth[] = [0, 50, 100, 200];
  return depths.map((depth) => {
    const stations = stationsInRegion(spec.region).filter((s) => s.depths.includes(depth));
    let n = 0, sa = 0, sb = 0;
    for (const s of stations) {
      for (let d = spec.fromDay; d <= spec.toDay; d += 3) {
        const diff = modelValue(s, spec.variable, depth, d) - observedValue(s, spec.variable, depth, d);
        sa += Math.abs(diff);
        sb += diff;
        n++;
      }
    }
    return { depth, mae: n ? +(sa / n).toFixed(3) : 0, bias: n ? +(sb / n).toFixed(3) : 0, n };
  }).filter((d) => d.n > 0);
}

export function errorHistogram(spec: FilterSpec): ErrorBin[] {
  const def = variableByKey(spec.variable);
  const edges = [0, def.goodBelow, def.moderateBelow, def.moderateBelow * 1.8, Infinity];
  const labels = [
    `0 – ${def.goodBelow}`,
    `${def.goodBelow} – ${def.moderateBelow}`,
    `${def.moderateBelow} – ${(def.moderateBelow * 1.8).toFixed(1)}`,
    `> ${(def.moderateBelow * 1.8).toFixed(1)}`,
  ];
  const counts = [0, 0, 0, 0];
  for (const r of matchRecords(spec)) {
    const a = Math.abs(r.diff);
    for (let i = 0; i < 4; i++) {
      if (a >= edges[i] && a < edges[i + 1]) {
        counts[i]++;
        break;
      }
    }
  }
  return labels.map((range, i) => ({ range: `${range} ${def.unit}`, count: counts[i] }));
}

/** Mean |error| on a coarse lon/lat grid — used by the error heatmap. */
export function errorGrid(spec: FilterSpec, step = 2): ErrorCell[] {
  const region = regionByKey(spec.region);
  const cells: ErrorCell[] = [];
  const stations = stationsInRegion(spec.region).filter((s) => s.depths.includes(spec.depth));
  for (let lon = region.bbox.lonMin + step / 2; lon < region.bbox.lonMax; lon += step) {
    for (let lat = region.bbox.latMin + step / 2; lat < region.bbox.latMax; lat += step) {
      if (isLand(lon, lat)) continue;
      // blend of distance to nearest stations: nearby stations anchor the error field
      let best = Infinity;
      let err = 0;
      for (const s of stations) {
        const dist = Math.hypot(s.lon - lon, s.lat - lat);
        if (dist < best) {
          best = dist;
          err = Math.abs(
            noise(`${s.id}|${spec.variable}|${spec.depth}|bias`, 1) *
              (spec.variable === "temperature" ? 0.42 : spec.variable === "salinity" ? 0.2 : 0.11) *
              (1 + spec.depth / 120) +
              (HIGH_DEV_STATIONS.has(s.id) ? 0.5 * (spec.variable === "salinity" ? 0.4 : 1) : 0)
          );
        }
      }
      const falloff = clamp(1.35 - best / 9, 0.25, 1.1);
      cells.push({ lon, lat, error: +(err * falloff).toFixed(3) });
    }
  }
  return cells;
}

/** Plain-language interpretation, generated with simple rules (no AI). */
export function interpretationFor(spec: FilterSpec): string[] {
  const depths = depthAgreement(spec);
  const metrics = validationMetrics(spec);
  const def = variableByKey(spec.variable);
  const region = regionByKey(spec.region);
  if (!depths.length) return ["No matched records available for the current filters."];
  const best = depths.reduce((a, b) => (a.mae <= b.mae ? a : b));
  const worst = depths.reduce((a, b) => (a.mae >= b.mae ? a : b));
  const out: string[] = [];
  const depthName = (d: number) => (d === 0 ? "the surface (0 m)" : `${d} m depth`);
  if (best.depth === worst.depth) {
    out.push(`Model agreement is consistent across the sampled depth layers in the selected ${region.label} region.`);
  } else {
    out.push(
      `Model performance is strongest at ${depthName(best.depth)} (MAE ${best.mae.toFixed(2)} ${def.unit}) and weakest at ${depthName(worst.depth)} (MAE ${worst.mae.toFixed(2)} ${def.unit}) in the selected ${region.label} region.`
    );
  }
  if (metrics.bias < -0.05) {
    out.push(`The model shows a cool/low bias of ${metrics.bias.toFixed(2)} ${def.unit}: predicted values are on average lower than the measurements.`);
  } else if (metrics.bias > 0.05) {
    out.push(`The model shows a warm/high bias of +${metrics.bias.toFixed(2)} ${def.unit}: predicted values are on average higher than the measurements.`);
  } else {
    out.push("Mean bias is close to zero: model and observations agree well on average.");
  }
  if (worst.depth >= 100) {
    out.push("Larger deviations below the thermocline may reflect unresolved subsurface mixing in the model's vertical scheme.");
  }
  return out;
}

/** Narrative for a single station snapshot. */
export function snapshotNarrative(variable: VariableKey, diff: number, depth: number): string {
  const def = variableByKey(variable);
  const a = Math.abs(diff);
  const depthText = depth === 0 ? "near the surface" : `at ${depth} m depth`;
  if (a < def.goodBelow) {
    return `Model and observation differ by only ${a.toFixed(2)} ${def.unit} ${depthText} — the model reproduces conditions here reliably.`;
  }
  const direction = diff < 0 ? "underestimates" : "overestimates";
  const what = variable === "temperature" ? "the observed temperature" : variable === "salinity" ? "the observed salinity" : "the observed current speed";
  return `The model ${direction} ${what} by ${a.toFixed(2)} ${def.unit} at this location ${depthText}.`;
}
